### ISSUE TITLE
Discrepancy between the PatternMonitoringDelivery specification and the XSD

### ISSUE THREAD

**Issue by hmb** [ITxPT/S02#2]
In the PDF specification of the AVMS service S02P06v2.1.0_ITxPT_AVMS_Service_specification.pdf there's an extension element in the PatternMonitoringDelivery structure:

PatternMonitoringDelivery | | | +Structure | Describes    the operational state of the current pattern.
-- | -- | -- | -- | --
Attributes | version | 1:1 | string | Version Identifier of Pattern Monitoring   Operation. This is the  version of the specification implemented. Fixed, e.g.   ‘2.1.0’.
Payload | MonitoredPattern | 1:1 | +Structure | Describes the pattern run by the vehicle.   When the vehicle is in  DeadRun state,   | PatternMonitoringDelivery is distributed without  MonitoredPattern structure.
Payload | MonitoredPatternCancellation | 0:1 | +Structure | Reference to a previously communicated MonitoredPattern ­which  should   not now be used.   When the vehicle is in DeadRun state,    PatternMonitoringDelivery is distributed without MonitoredPatternCancellation   structure.
**any** | **Extensions** | **0:1** | **anyType** | **Placeholder for user extensions.**

This extension element is not in the according xsd:

```xml
  <xs:element name="PatternMonitoringDelivery">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="MonitoredPattern"/>
        <xs:element minOccurs="0" ref="MonitoredPatternCancellation"/>
      </xs:sequence>
      <xs:attribute name="version" use="required" type="xs:string"/>
    </xs:complexType>
  </xs:element>
```

[PatternMonitoringDelivery.xsd](https://github.com/ITxPT/S02/blob/0a9da649905d739824b218b7844c7a59fa75ee3f/xsd/S02P06_avms/PatternMonitoringDelivery.xsd)

**Comment by victorDARDENNE** [comment]
Fixed - [6bf3a9d](https://github.com/ITxPT/S02/commit/6bf3a9d5db62642ef4c13b5dc2d4501553b3ed16)
